In [26]:
import numpy as np

In [27]:

N=8

In [28]:
# difine a dictionary varibale which cached our result.for every state the board where queen palced on it
# it cached the result whether the board is safe ot not
board_state_memory={}

In [29]:
# initialize two dimensional  NumPy array it 8X8
board=np.zeros((N,N),np.int8)

In [30]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [31]:
# now create a function which reperesent an N by N board in string from
def create_board_string(board):
    board_string=''
    for i in range(N):
        for j in range(N):
            board_string+=str(board[i][j])
    return board_string    

In [32]:
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [33]:
# lets define is_board_safe function check whether is board safe or not
def is_board_safe(board):
      
    board_key=create_board_string(board)
    if board_key in board_state_memory:
        print("using cached inforamtion")
        return board_state_memory[board_key] #it return true if boar is safe and return false if board in not safe


#calculate the sum of every row
#if row sum > 1 that means that row has more than queen then current state of the board is not safe
    row_sum=np.sum(board,axis=1)
    if len(row_sum[np.where(row_sum > 1)]) > 0:
        board_state_memory[board_key]= False
        return False
# smae as we can do for column
    col_sum=np.sum(board,axis=1)
    if len(col_sum[np.where(col_sum > 1)]) > 0:
        board_state_memory[board_key]= False
        return False
# same as we  can do for diagonal 
    diags=[board[::-1,:].diagonal(i) for i in range(-board.shape[0] +1,board.shape[1])]
    diags.extend(board.diagonal(i) for i in range(board.shape[1] -1 ,board.shape[0],-1))
    for diag in diags:
        if np.sum(diag) > 1:
            board_state_memory[board_key]=False
            return False
    board_state_memory[board_key]=True
    return True



In [37]:
board_copy=board.copy()

In [38]:
board_copy[0][0]=1
board_copy[0][6]=1


In [39]:
print(board_copy)
is_board_safe(board_copy)

[[1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [40]:
# Now maske a function which placed all queen
def place_queen(board,column):
    if column>=N:
        return True
    for row in range(N):
        board[row][column]=1
        
        
        safe=False
        if is_board_safe(board): 
            safe=place_queen(board,column+1)
        if not safe:
            board[row][column]=0
        else:
            break
    return safe


In [41]:
board_state_memory

{'0000000010000000100000000000000000000000000000000000000000000000': True,
 '1000001000000000000000000000000000000000000000000000000000000000': False}

In [42]:
#lets initialize again our chess board
board=np.zeros((N,N),np.int8)

In [43]:
x=place_queen(board,0)


In [44]:
x

True